<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en-US" xml:lang="en-US"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>113&nbsp; Compound Forms, Prefixes, Suffixes, and Naming Runes – The Grimoire of Software Magic Words</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../reference/house-failure-words-pathologies-and-counter-spells.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-39ac65d2ba81e8f361d24188b4938e12.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../reference/lexicon.html">Master Lexicon</a></li><li class="breadcrumb-item"><a href="../reference/house-compound-forms-prefixes-suffixes-and-naming-runes.html"><span class="chapter-number">113</span>&nbsp; <span class="chapter-title">Compound Forms, Prefixes, Suffixes, and Naming Runes</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">The Grimoire of Software Magic Words</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/corbensorenson/software-grimoire" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">The Grimoire of Software Magic Words</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../quick_start.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">First Spell in Five Minutes</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reader_path.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Guided Reader Path</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Core Grimoire</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../porting-status.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Porting Status</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Preface</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/01-operative-language.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Operative Language</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/02-what-a-spell-is.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">What a Spell Is</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/03-crafting-spells.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Crafting Spells</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/04-sigils-canonicalization-and-seals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Sigils, Canonicalization, and Seals</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/05-coil-inspection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Coil Inspection</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/06-field-spells.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Field Spells</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/07-public-canon.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">The Public Canon</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/08-stackcraft.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Stackcraft</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/09-tooling-and-formalization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Tooling and Formalization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/10-living-practice.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Living Practice</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/11-adversarial-promptcraft.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Adversarial Promptcraft</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Spell Library</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../spells/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Spell Library</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../spells/safe-refactoring.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Spell of Safe Refactoring</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../spells/bug-diagnosis-from-logs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Spell of Bug Diagnosis from Logs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../spells/api-design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Spell of API Design</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../spells/migration-without-data-loss.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Spell of Migration Without Data Loss</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../spells/test-generation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Spell of Test Generation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../spells/performance-tuning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Spell of Performance Tuning</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../spells/jailbreak-resilience-review.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Spell of Jailbreak-Resilience Review</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Stack Library</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../stacks/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Stack Library</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../stacks/code-generation-and-repair-loop.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Code Generation and Repair Loop</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../stacks/bug-hunt-stack.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Bug-Hunt Stack</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../stacks/safe-refactor-stack.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Safe Refactor Stack</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../stacks/live-migration-stack.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Live Migration Stack</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../stacks/release-gate-stack.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Release Gate Stack</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../stacks/recursive-decomposition-stack.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Recursive Decomposition Stack</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../stacks/ai-red-team-loop.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">AI Red-Team Loop</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Proof by Difference Cases</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/weak-vs-repaired/safe-refactoring.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Refactor Without Breaking Behavior</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/weak-vs-repaired/bug-diagnosis-from-logs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Incident Diagnosis Without Fake Certainty</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/weak-vs-repaired/api-design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">API Design Without Hidden Compatibility Traps</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/weak-vs-repaired/migration-without-data-loss.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Online Migration Without Data Loss</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/weak-vs-repaired/test-generation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Test Generation Without Overfitting To Implementation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/weak-vs-repaired/performance-tuning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Performance Tuning Without Micro-Optimization Drift</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Recorded Evaluations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/evaluations/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Recorded Evaluations</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/evaluations/safe-refactoring.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">Refactor Without Breaking Behavior</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/evaluations/bug-diagnosis-from-logs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">Incident Diagnosis Without Fake Certainty</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/evaluations/api-design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">API Design Without Hidden Compatibility Traps</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/evaluations/migration-without-data-loss.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">Online Migration Without Data Loss</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/evaluations/test-generation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">44</span>&nbsp; <span class="chapter-title">Test Generation Without Overfitting To Implementation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/evaluations/performance-tuning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">45</span>&nbsp; <span class="chapter-title">Performance Tuning Without Micro-Optimization Drift</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Jailbreak Resilience</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/jailbreak-resilience/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">46</span>&nbsp; <span class="chapter-title">Jailbreak-Resilience Bench</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/jailbreak-resilience/indirect-readme-injection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">47</span>&nbsp; <span class="chapter-title">Indirect README Injection</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/jailbreak-resilience/tainted-log-instruction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">48</span>&nbsp; <span class="chapter-title">Tainted Log Instruction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/jailbreak-resilience/rag-chunk-override.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">49</span>&nbsp; <span class="chapter-title">RAG Chunk Override</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/jailbreak-resilience/system-prompt-leak-request.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">50</span>&nbsp; <span class="chapter-title">System-Prompt Leak Request</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/jailbreak-resilience/multi-turn-scope-creep.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">51</span>&nbsp; <span class="chapter-title">Multi-Turn Scope Creep</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/jailbreak-resilience/many-shot-policy-drift.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">52</span>&nbsp; <span class="chapter-title">Many-Shot Policy Drift</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/jailbreak-resilience/forbidden-tool-call.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">53</span>&nbsp; <span class="chapter-title">Forbidden Tool Call</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/jailbreak-resilience/canary-leakage.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">54</span>&nbsp; <span class="chapter-title">Canary Leakage</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text">Adoption Kit</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../adoption/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">55</span>&nbsp; <span class="chapter-title">Adoption Kit</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../adoption/installable-library.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">56</span>&nbsp; <span class="chapter-title">Installable Library</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../adoption/evidence.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">57</span>&nbsp; <span class="chapter-title">Adoption Evidence</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../adoption/playbook.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">58</span>&nbsp; <span class="chapter-title">Adoption Playbook</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../adoption/external-walkthrough.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">59</span>&nbsp; <span class="chapter-title">External Walkthrough</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true">
 <span class="menu-text">Reference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reference/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">60</span>&nbsp; <span class="chapter-title">Reference</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reference/cast-levels.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">61</span>&nbsp; <span class="chapter-title">Cast Levels</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reference/spell-skeleton.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">62</span>&nbsp; <span class="chapter-title">Canonical Spell Skeleton</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reference/stack-grammar.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">63</span>&nbsp; <span class="chapter-title">Stack Grammar</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reference/seals-and-sigils.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">64</span>&nbsp; <span class="chapter-title">Seals and Sigils</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reference/failure-modes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">65</span>&nbsp; <span class="chapter-title">Failure Modes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reference/proof-by-difference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">66</span>&nbsp; <span class="chapter-title">Proof by Difference</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reference/evidence-browser.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">67</span>&nbsp; <span class="chapter-title">Evidence Browser</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reference/calibration.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">68</span>&nbsp; <span class="chapter-title">Calibration</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reference/bench-v2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">69</span>&nbsp; <span class="chapter-title">Bench v2</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reference/execution-bench.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">70</span>&nbsp; <span class="chapter-title">Execution-Graded Bench</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reference/hardness-v4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">71</span>&nbsp; <span class="chapter-title">Bench v4 Hardness Ladder</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reference/model-artifact-execution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">72</span>&nbsp; <span class="chapter-title">Model Artifact Execution</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reference/surface-comparison.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">73</span>&nbsp; <span class="chapter-title">Surface Comparison</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reference/jailbreak-resilience.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">74</span>&nbsp; <span class="chapter-title">Jailbreak Resilience</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reference/adversarial-harness.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">75</span>&nbsp; <span class="chapter-title">Adversarial Harness v2</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reference/warded-baselines.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">76</span>&nbsp; <span class="chapter-title">Warded Baselines</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reference/ward-science.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">77</span>&nbsp; <span class="chapter-title">Ward Science</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reference/warded-ab-evidence.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">78</span>&nbsp; <span class="chapter-title">Warded A/B Evidence</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reference/semantic-promotion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">79</span>&nbsp; <span class="chapter-title">Semantic Promotion Ladder</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reference/canon-audit.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">80</span>&nbsp; <span class="chapter-title">Canon Audit</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reference/usage-earned-canon.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">81</span>&nbsp; <span class="chapter-title">Usage-Earned Canon</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reference/canon-review-queue.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">82</span>&nbsp; <span class="chapter-title">Canon Review Queue</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reference/methods-structure-reviewability-warding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">83</span>&nbsp; <span class="chapter-title">Methods: Structure, Reviewability, and Warding</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reference/logical-conclusion-status.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">84</span>&nbsp; <span class="chapter-title">Logical Conclusion Status</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reference/public-smoke-checks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">85</span>&nbsp; <span class="chapter-title">Public Smoke Checks</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reference/package-index-release.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">86</span>&nbsp; <span class="chapter-title">Package-Index Release Plan</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reference/generator-architecture.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">87</span>&nbsp; <span class="chapter-title">Generator Architecture</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reference/visual-grammar.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">88</span>&nbsp; <span class="chapter-title">Visual Grammar</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reference/task-chooser.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">89</span>&nbsp; <span class="chapter-title">Task Chooser</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reference/canon-map.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">90</span>&nbsp; <span class="chapter-title">Canon Map</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reference/major-canon.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">91</span>&nbsp; <span class="chapter-title">The Fifty World-Running Words</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reference/pocket-canon.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">92</span>&nbsp; <span class="chapter-title">Pocket Canon</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reference/pocket-field-guide.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">93</span>&nbsp; <span class="chapter-title">Pocket Field Guide</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reference/term-index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">94</span>&nbsp; <span class="chapter-title">Term Index</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="true">
 <span class="menu-text">Master Lexicon</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reference/lexicon.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">95</span>&nbsp; <span class="chapter-title">Master Lexicon</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reference/house-architecture-abstraction-and-design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">96</span>&nbsp; <span class="chapter-title">Architecture, Abstraction, and Design</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reference/house-language-semantics-and-formal-shape.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">97</span>&nbsp; <span class="chapter-title">Language, Semantics, and Formal Shape</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reference/house-data-state-and-representation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">98</span>&nbsp; <span class="chapter-title">Data, State, and Representation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reference/house-transformation-algorithms-and-working-verbs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">99</span>&nbsp; <span class="chapter-title">Transformation, Algorithms, and Working Verbs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reference/house-control-flow-coordination-and-temporal-logic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">100</span>&nbsp; <span class="chapter-title">Control Flow, Coordination, and Temporal Logic</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reference/house-runtime-memory-and-execution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">101</span>&nbsp; <span class="chapter-title">Runtime, Memory, and Execution</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reference/house-systems-programming-and-operating-system-words.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">102</span>&nbsp; <span class="chapter-title">Systems Programming and Operating-System Words</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reference/house-networking-and-distributed-systems.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">103</span>&nbsp; <span class="chapter-title">Networking and Distributed Systems</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reference/house-databases-persistence-and-time-binding-words.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">104</span>&nbsp; <span class="chapter-title">Databases, Persistence, and Time-Binding Words</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reference/house-security-trust-and-warding-words.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">105</span>&nbsp; <span class="chapter-title">Security, Trust, and Warding Words</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reference/house-build-tooling-versioning-and-release.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">106</span>&nbsp; <span class="chapter-title">Build, Tooling, Versioning, and Release</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reference/house-testing-verification-and-observability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">107</span>&nbsp; <span class="chapter-title">Testing, Verification, and Observability</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reference/house-hardware-embedded-and-performance-near-words.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">108</span>&nbsp; <span class="chapter-title">Hardware, Embedded, and Performance-Near Words</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reference/house-interface-ux-and-human-facing-words.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">109</span>&nbsp; <span class="chapter-title">Interface, UX, and Human-Facing Words</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reference/house-promptcraft-ai-oriented-engineering-and-spell-structure.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">110</span>&nbsp; <span class="chapter-title">Promptcraft, AI-Oriented Engineering, and Spell Structure</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reference/house-guarantee-words-quality-attributes-and-behavioral-adjectives.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">111</span>&nbsp; <span class="chapter-title">Guarantee Words, Quality Attributes, and Behavioral Adjectives</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reference/house-failure-words-pathologies-and-counter-spells.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">112</span>&nbsp; <span class="chapter-title">Failure Words, Pathologies, and Counter-Spells</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reference/house-compound-forms-prefixes-suffixes-and-naming-runes.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">113</span>&nbsp; <span class="chapter-title">Compound Forms, Prefixes, Suffixes, and Naming Runes</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#compound-forms-prefixes-suffixes-and-naming-runes" id="toc-compound-forms-prefixes-suffixes-and-naming-runes" class="nav-link active" data-scroll-target="#compound-forms-prefixes-suffixes-and-naming-runes"><span class="header-section-number">114</span> Compound Forms, Prefixes, Suffixes, and Naming Runes</a>
  <ul class="collapse">
  <li><a href="#completion" id="toc-completion" class="nav-link" data-scroll-target="#completion"><span class="header-section-number">114.1</span> Completion</a></li>
  <li><a href="#entries" id="toc-entries" class="nav-link" data-scroll-target="#entries"><span class="header-section-number">114.2</span> Entries</a>
  <ul class="collapse">
  <li><a href="#rune-1583" id="toc-rune-1583" class="nav-link" data-scroll-target="#rune-1583"><span class="header-section-number">114.2.1</span> [1583] -able</a></li>
  <li><a href="#rune-1584" id="toc-rune-1584" class="nav-link" data-scroll-target="#rune-1584"><span class="header-section-number">114.2.2</span> [1584] -aware</a></li>
  <li><a href="#rune-1585" id="toc-rune-1585" class="nav-link" data-scroll-target="#rune-1585"><span class="header-section-number">114.2.3</span> [1585] -by-design</a></li>
  <li><a href="#rune-1586" id="toc-rune-1586" class="nav-link" data-scroll-target="#rune-1586"><span class="header-section-number">114.2.4</span> [1586] -centric</a></li>
  <li><a href="#rune-1587" id="toc-rune-1587" class="nav-link" data-scroll-target="#rune-1587"><span class="header-section-number">114.2.5</span> [1587] -complete</a></li>
  <li><a href="#rune-1588" id="toc-rune-1588" class="nav-link" data-scroll-target="#rune-1588"><span class="header-section-number">114.2.6</span> [1588] -driven</a></li>
  <li><a href="#rune-1589" id="toc-rune-1589" class="nav-link" data-scroll-target="#rune-1589"><span class="header-section-number">114.2.7</span> [1589] -first</a></li>
  <li><a href="#rune-1590" id="toc-rune-1590" class="nav-link" data-scroll-target="#rune-1590"><span class="header-section-number">114.2.8</span> [1590] -free</a></li>
  <li><a href="#rune-1591" id="toc-rune-1591" class="nav-link" data-scroll-target="#rune-1591"><span class="header-section-number">114.2.9</span> [1591] -friendly</a></li>
  <li><a href="#rune-1592" id="toc-rune-1592" class="nav-link" data-scroll-target="#rune-1592"><span class="header-section-number">114.2.10</span> [1592] -hard</a></li>
  <li><a href="#rune-1593" id="toc-rune-1593" class="nav-link" data-scroll-target="#rune-1593"><span class="header-section-number">114.2.11</span> [1593] -less</a></li>
  <li><a href="#rune-1594" id="toc-rune-1594" class="nav-link" data-scroll-target="#rune-1594"><span class="header-section-number">114.2.12</span> [1594] -local</a></li>
  <li><a href="#rune-1595" id="toc-rune-1595" class="nav-link" data-scroll-target="#rune-1595"><span class="header-section-number">114.2.13</span> [1595] -native</a></li>
  <li><a href="#rune-1596" id="toc-rune-1596" class="nav-link" data-scroll-target="#rune-1596"><span class="header-section-number">114.2.14</span> [1596] -of-record</a></li>
  <li><a href="#rune-1597" id="toc-rune-1597" class="nav-link" data-scroll-target="#rune-1597"><span class="header-section-number">114.2.15</span> [1597] -oriented</a></li>
  <li><a href="#rune-1598" id="toc-rune-1598" class="nav-link" data-scroll-target="#rune-1598"><span class="header-section-number">114.2.16</span> [1598] -safe</a></li>
  <li><a href="#rune-1599" id="toc-rune-1599" class="nav-link" data-scroll-target="#rune-1599"><span class="header-section-number">114.2.17</span> [1599] -sensitive</a></li>
  <li><a href="#rune-1600" id="toc-rune-1600" class="nav-link" data-scroll-target="#rune-1600"><span class="header-section-number">114.2.18</span> [1600] -shaped</a></li>
  <li><a href="#rune-1601" id="toc-rune-1601" class="nav-link" data-scroll-target="#rune-1601"><span class="header-section-number">114.2.19</span> [1601] -soft</a></li>
  <li><a href="#rune-1602" id="toc-rune-1602" class="nav-link" data-scroll-target="#rune-1602"><span class="header-section-number">114.2.20</span> [1602] -tolerant</a></li>
  <li><a href="#rune-1603" id="toc-rune-1603" class="nav-link" data-scroll-target="#rune-1603"><span class="header-section-number">114.2.21</span> [1603] -wide</a></li>
  <li><a href="#rune-1604" id="toc-rune-1604" class="nav-link" data-scroll-target="#rune-1604"><span class="header-section-number">114.2.22</span> [1604] actor model</a></li>
  <li><a href="#rune-1605" id="toc-rune-1605" class="nav-link" data-scroll-target="#rune-1605"><span class="header-section-number">114.2.23</span> [1605] API-first</a></li>
  <li><a href="#rune-1606" id="toc-rune-1606" class="nav-link" data-scroll-target="#rune-1606"><span class="header-section-number">114.2.24</span> [1606] append-only</a></li>
  <li><a href="#rune-1607" id="toc-rune-1607" class="nav-link" data-scroll-target="#rune-1607"><span class="header-section-number">114.2.25</span> [1607] best-effort</a></li>
  <li><a href="#rune-1608" id="toc-rune-1608" class="nav-link" data-scroll-target="#rune-1608"><span class="header-section-number">114.2.26</span> [1608] branch-free</a></li>
  <li><a href="#rune-1609" id="toc-rune-1609" class="nav-link" data-scroll-target="#rune-1609"><span class="header-section-number">114.2.27</span> [1609] cloud-native</a></li>
  <li><a href="#rune-1610" id="toc-rune-1610" class="nav-link" data-scroll-target="#rune-1610"><span class="header-section-number">114.2.28</span> [1610] command-query</a></li>
  <li><a href="#rune-1611" id="toc-rune-1611" class="nav-link" data-scroll-target="#rune-1611"><span class="header-section-number">114.2.29</span> [1611] control plane {Rune}</a></li>
  <li><a href="#rune-1612" id="toc-rune-1612" class="nav-link" data-scroll-target="#rune-1612"><span class="header-section-number">114.2.30</span> [1612] copy-on-write {Rune}</a></li>
  <li><a href="#rune-1613" id="toc-rune-1613" class="nav-link" data-scroll-target="#rune-1613"><span class="header-section-number">114.2.31</span> [1613] crash-only</a></li>
  <li><a href="#rune-1614" id="toc-rune-1614" class="nav-link" data-scroll-target="#rune-1614"><span class="header-section-number">114.2.32</span> [1614] data plane {Rune}</a></li>
  <li><a href="#rune-1615" id="toc-rune-1615" class="nav-link" data-scroll-target="#rune-1615"><span class="header-section-number">114.2.33</span> [1615] data-driven</a></li>
  <li><a href="#rune-1616" id="toc-rune-1616" class="nav-link" data-scroll-target="#rune-1616"><span class="header-section-number">114.2.34</span> [1616] default-deny</a></li>
  <li><a href="#rune-1617" id="toc-rune-1617" class="nav-link" data-scroll-target="#rune-1617"><span class="header-section-number">114.2.35</span> [1617] edge-native</a></li>
  <li><a href="#rune-1618" id="toc-rune-1618" class="nav-link" data-scroll-target="#rune-1618"><span class="header-section-number">114.2.36</span> [1618] event-driven</a></li>
  <li><a href="#rune-1619" id="toc-rune-1619" class="nav-link" data-scroll-target="#rune-1619"><span class="header-section-number">114.2.37</span> [1619] eventually consistent</a></li>
  <li><a href="#rune-1620" id="toc-rune-1620" class="nav-link" data-scroll-target="#rune-1620"><span class="header-section-number">114.2.38</span> [1620] fail-fast</a></li>
  <li><a href="#rune-1621" id="toc-rune-1621" class="nav-link" data-scroll-target="#rune-1621"><span class="header-section-number">114.2.39</span> [1621] first-class</a></li>
  <li><a href="#rune-1622" id="toc-rune-1622" class="nav-link" data-scroll-target="#rune-1622"><span class="header-section-number">114.2.40</span> [1622] hot path {Rune}</a></li>
  <li><a href="#rune-1623" id="toc-rune-1623" class="nav-link" data-scroll-target="#rune-1623"><span class="header-section-number">114.2.41</span> [1623] infrastructure-as-code</a></li>
  <li><a href="#rune-1624" id="toc-rune-1624" class="nav-link" data-scroll-target="#rune-1624"><span class="header-section-number">114.2.42</span> [1624] least-authority</a></li>
  <li><a href="#rune-1625" id="toc-rune-1625" class="nav-link" data-scroll-target="#rune-1625"><span class="header-section-number">114.2.43</span> [1625] lock-free {Rune}</a></li>
  <li><a href="#rune-1626" id="toc-rune-1626" class="nav-link" data-scroll-target="#rune-1626"><span class="header-section-number">114.2.44</span> [1626] machine-readable</a></li>
  <li><a href="#rune-1627" id="toc-rune-1627" class="nav-link" data-scroll-target="#rune-1627"><span class="header-section-number">114.2.45</span> [1627] memory-safe {Rune}</a></li>
  <li><a href="#rune-1628" id="toc-rune-1628" class="nav-link" data-scroll-target="#rune-1628"><span class="header-section-number">114.2.46</span> [1628] multi-tenant</a></li>
  <li><a href="#rune-1629" id="toc-rune-1629" class="nav-link" data-scroll-target="#rune-1629"><span class="header-section-number">114.2.47</span> [1629] negative cache</a></li>
  <li><a href="#rune-1630" id="toc-rune-1630" class="nav-link" data-scroll-target="#rune-1630"><span class="header-section-number">114.2.48</span> [1630] object-capability</a></li>
  <li><a href="#rune-1631" id="toc-rune-1631" class="nav-link" data-scroll-target="#rune-1631"><span class="header-section-number">114.2.49</span> [1631] offline-first {Rune}</a></li>
  <li><a href="#rune-1632" id="toc-rune-1632" class="nav-link" data-scroll-target="#rune-1632"><span class="header-section-number">114.2.50</span> [1632] policy-as-code</a></li>
  <li><a href="#rune-1633" id="toc-rune-1633" class="nav-link" data-scroll-target="#rune-1633"><span class="header-section-number">114.2.51</span> [1633] queue-backed</a></li>
  <li><a href="#rune-1634" id="toc-rune-1634" class="nav-link" data-scroll-target="#rune-1634"><span class="header-section-number">114.2.52</span> [1634] read path</a></li>
  <li><a href="#rune-1635" id="toc-rune-1635" class="nav-link" data-scroll-target="#rune-1635"><span class="header-section-number">114.2.53</span> [1635] read-through cache</a></li>
  <li><a href="#rune-1636" id="toc-rune-1636" class="nav-link" data-scroll-target="#rune-1636"><span class="header-section-number">114.2.54</span> [1636] real-time {Rune}</a></li>
  <li><a href="#rune-1637" id="toc-rune-1637" class="nav-link" data-scroll-target="#rune-1637"><span class="header-section-number">114.2.55</span> [1637] rule-based</a></li>
  <li><a href="#rune-1638" id="toc-rune-1638" class="nav-link" data-scroll-target="#rune-1638"><span class="header-section-number">114.2.56</span> [1638] side-effect-free {Rune}</a></li>
  <li><a href="#rune-1639" id="toc-rune-1639" class="nav-link" data-scroll-target="#rune-1639"><span class="header-section-number">114.2.57</span> [1639] single source of truth</a></li>
  <li><a href="#rune-1640" id="toc-rune-1640" class="nav-link" data-scroll-target="#rune-1640"><span class="header-section-number">114.2.58</span> [1640] soft delete</a></li>
  <li><a href="#rune-1641" id="toc-rune-1641" class="nav-link" data-scroll-target="#rune-1641"><span class="header-section-number">114.2.59</span> [1641] statefulset</a></li>
  <li><a href="#rune-1642" id="toc-rune-1642" class="nav-link" data-scroll-target="#rune-1642"><span class="header-section-number">114.2.60</span> [1642] write path</a></li>
  <li><a href="#rune-1643" id="toc-rune-1643" class="nav-link" data-scroll-target="#rune-1643"><span class="header-section-number">114.2.61</span> [1643] write-through cache</a></li>
  <li><a href="#rune-1644" id="toc-rune-1644" class="nav-link" data-scroll-target="#rune-1644"><span class="header-section-number">114.2.62</span> [1644] zero-downtime</a></li>
  <li><a href="#rune-1645" id="toc-rune-1645" class="nav-link" data-scroll-target="#rune-1645"><span class="header-section-number">114.2.63</span> [1645] zero-knowledge</a></li>
  </ul></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/corbensorenson/software-grimoire/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li><li><a href="https://github.com/corbensorenson/software-grimoire/blob/main/reference/house-compound-forms-prefixes-suffixes-and-naming-runes.qmd" class="toc-action"><i class="bi empty"></i>View source</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../reference/lexicon.html">Master Lexicon</a></li><li class="breadcrumb-item"><a href="../reference/house-compound-forms-prefixes-suffixes-and-naming-runes.html"><span class="chapter-number">113</span>&nbsp; <span class="chapter-title">Compound Forms, Prefixes, Suffixes, and Naming Runes</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">113</span>&nbsp; <span class="chapter-title">Compound Forms, Prefixes, Suffixes, and Naming Runes</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="compound-forms-prefixes-suffixes-and-naming-runes" class="level1" data-number="114">
<h1 data-number="114"><span class="header-section-number">114</span> Compound Forms, Prefixes, Suffixes, and Naming Runes</h1>
<p>Range: <code>1583-1645</code>.</p>
<section id="completion" class="level2" data-number="114.1">
<h2 data-number="114.1" class="anchored" data-anchor-id="completion"><span class="header-section-number">114.1</span> Completion</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Status</th>
<th>Count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>authored</td>
<td>63</td>
</tr>
</tbody>
</table>
<p>Use the summary table for scanning. Each row links to the detailed anchored entry below.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Sigil</th>
<th>Term</th>
<th>Completion</th>
<th>Semantic</th>
<th>Summary</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1583</td>
<td><a href="#rune-1583">-able</a></td>
<td>authored</td>
<td>generated_draft</td>
<td><code>-able</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the -able obligation named before work proceeds.</td>
</tr>
<tr class="even">
<td>1584</td>
<td><a href="#rune-1584">-aware</a></td>
<td>authored</td>
<td>reviewed</td>
<td>Marks that something notices the surrounding condition it names.</td>
</tr>
<tr class="odd">
<td>1585</td>
<td><a href="#rune-1585">-by-design</a></td>
<td>authored</td>
<td>generated_draft</td>
<td><code>-by-design</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the -by-design obligation named before work proceeds.</td>
</tr>
<tr class="even">
<td>1586</td>
<td><a href="#rune-1586">-centric</a></td>
<td>authored</td>
<td>generated_draft</td>
<td><code>-centric</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the -centric obligation named before work proceeds.</td>
</tr>
<tr class="odd">
<td>1587</td>
<td><a href="#rune-1587">-complete</a></td>
<td>authored</td>
<td>generated_draft</td>
<td><code>-complete</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the -complete obligation named before work proceeds.</td>
</tr>
<tr class="even">
<td>1588</td>
<td><a href="#rune-1588">-driven</a></td>
<td>authored</td>
<td>reviewed</td>
<td>Signals that behavior is organized around events or causes.</td>
</tr>
<tr class="odd">
<td>1589</td>
<td><a href="#rune-1589">-first</a></td>
<td>authored</td>
<td>reviewed</td>
<td>Declares priority or design center: security-first, API-first, offline-first.</td>
</tr>
<tr class="even">
<td>1590</td>
<td><a href="#rune-1590">-free</a></td>
<td>authored</td>
<td>generated_draft</td>
<td><code>-free</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the -free obligation named before work proceeds.</td>
</tr>
<tr class="odd">
<td>1591</td>
<td><a href="#rune-1591">-friendly</a></td>
<td>authored</td>
<td>generated_draft</td>
<td><code>-friendly</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the -friendly obligation named before work proceeds.</td>
</tr>
<tr class="even">
<td>1592</td>
<td><a href="#rune-1592">-hard</a></td>
<td>authored</td>
<td>generated_draft</td>
<td><code>-hard</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the -hard obligation named before work proceeds.</td>
</tr>
<tr class="odd">
<td>1593</td>
<td><a href="#rune-1593">-less</a></td>
<td>authored</td>
<td>generated_draft</td>
<td><code>-less</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the -less obligation named before work proceeds.</td>
</tr>
<tr class="even">
<td>1594</td>
<td><a href="#rune-1594">-local</a></td>
<td>authored</td>
<td>generated_draft</td>
<td><code>-local</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the -local obligation named before work proceeds.</td>
</tr>
<tr class="odd">
<td>1595</td>
<td><a href="#rune-1595">-native</a></td>
<td>authored</td>
<td>generated_draft</td>
<td><code>-native</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the -native obligation named before work proceeds.</td>
</tr>
<tr class="even">
<td>1596</td>
<td><a href="#rune-1596">-of-record</a></td>
<td>authored</td>
<td>generated_draft</td>
<td><code>-of-record</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the -of-record obligation named before work proceeds.</td>
</tr>
<tr class="odd">
<td>1597</td>
<td><a href="#rune-1597">-oriented</a></td>
<td>authored</td>
<td>generated_draft</td>
<td><code>-oriented</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the -oriented obligation named before work proceeds.</td>
</tr>
<tr class="even">
<td>1598</td>
<td><a href="#rune-1598">-safe</a></td>
<td>authored</td>
<td>reviewed</td>
<td>Asserts a protected behavior such as memory-safe or thread-safe.</td>
</tr>
<tr class="odd">
<td>1599</td>
<td><a href="#rune-1599">-sensitive</a></td>
<td>authored</td>
<td>generated_draft</td>
<td><code>-sensitive</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the -sensitive obligation named before work proceeds.</td>
</tr>
<tr class="even">
<td>1600</td>
<td><a href="#rune-1600">-shaped</a></td>
<td>authored</td>
<td>generated_draft</td>
<td><code>-shaped</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the -shaped obligation named before work proceeds.</td>
</tr>
<tr class="odd">
<td>1601</td>
<td><a href="#rune-1601">-soft</a></td>
<td>authored</td>
<td>generated_draft</td>
<td><code>-soft</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the -soft obligation named before work proceeds.</td>
</tr>
<tr class="even">
<td>1602</td>
<td><a href="#rune-1602">-tolerant</a></td>
<td>authored</td>
<td>generated_draft</td>
<td><code>-tolerant</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the -tolerant obligation named before work proceeds.</td>
</tr>
<tr class="odd">
<td>1603</td>
<td><a href="#rune-1603">-wide</a></td>
<td>authored</td>
<td>generated_draft</td>
<td><code>-wide</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the -wide obligation named before work proceeds.</td>
</tr>
<tr class="even">
<td>1604</td>
<td><a href="#rune-1604">actor model</a></td>
<td>authored</td>
<td>generated_draft</td>
<td><code>actor model</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the actor model obligation named before work proceeds.</td>
</tr>
<tr class="odd">
<td>1605</td>
<td><a href="#rune-1605">API-first</a></td>
<td>authored</td>
<td>reviewed</td>
<td>Design the interface surface before the implementations behind it.</td>
</tr>
<tr class="even">
<td>1606</td>
<td><a href="#rune-1606">append-only</a></td>
<td>authored</td>
<td>reviewed</td>
<td>History grows by addition rather than mutation.</td>
</tr>
<tr class="odd">
<td>1607</td>
<td><a href="#rune-1607">best-effort</a></td>
<td>authored</td>
<td>generated_draft</td>
<td><code>best-effort</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the best-effort obligation named before work proceeds.</td>
</tr>
<tr class="even">
<td>1608</td>
<td><a href="#rune-1608">branch-free</a></td>
<td>authored</td>
<td>generated_draft</td>
<td><code>branch-free</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the branch-free obligation named before work proceeds.</td>
</tr>
<tr class="odd">
<td>1609</td>
<td><a href="#rune-1609">cloud-native</a></td>
<td>authored</td>
<td>generated_draft</td>
<td><code>cloud-native</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the cloud-native obligation named before work proceeds.</td>
</tr>
<tr class="even">
<td>1610</td>
<td><a href="#rune-1610">command-query</a></td>
<td>authored</td>
<td>generated_draft</td>
<td><code>command-query</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the command-query obligation named before work proceeds.</td>
</tr>
<tr class="odd">
<td>1611</td>
<td><a href="#rune-1611">control plane {Rune}</a></td>
<td>authored</td>
<td>generated_draft</td>
<td><code>control plane</code> in its Rune sense is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the control plane obligation named before work proceeds.</td>
</tr>
<tr class="even">
<td>1612</td>
<td><a href="#rune-1612">copy-on-write {Rune}</a></td>
<td>authored</td>
<td>generated_draft</td>
<td><code>copy-on-write</code> in its Rune sense is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the copy-on-write obligation named before work proceeds.</td>
</tr>
<tr class="odd">
<td>1613</td>
<td><a href="#rune-1613">crash-only</a></td>
<td>authored</td>
<td>reviewed</td>
<td>Only live briefly, start fast, and recover by restart rather than repair.</td>
</tr>
<tr class="even">
<td>1614</td>
<td><a href="#rune-1614">data plane {Rune}</a></td>
<td>authored</td>
<td>generated_draft</td>
<td><code>data plane</code> in its Rune sense is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the data plane obligation named before work proceeds.</td>
</tr>
<tr class="odd">
<td>1615</td>
<td><a href="#rune-1615">data-driven</a></td>
<td>authored</td>
<td>generated_draft</td>
<td><code>data-driven</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the data-driven obligation named before work proceeds.</td>
</tr>
<tr class="even">
<td>1616</td>
<td><a href="#rune-1616">default-deny</a></td>
<td>authored</td>
<td>reviewed</td>
<td>Access is forbidden unless explicitly granted.</td>
</tr>
<tr class="odd">
<td>1617</td>
<td><a href="#rune-1617">edge-native</a></td>
<td>authored</td>
<td>generated_draft</td>
<td><code>edge-native</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the edge-native obligation named before work proceeds.</td>
</tr>
<tr class="even">
<td>1618</td>
<td><a href="#rune-1618">event-driven</a></td>
<td>authored</td>
<td>reviewed</td>
<td>Action propagates from events rather than from direct polling or command loops.</td>
</tr>
<tr class="odd">
<td>1619</td>
<td><a href="#rune-1619">eventually consistent</a></td>
<td>authored</td>
<td>generated_draft</td>
<td><code>eventually consistent</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the eventually consistent obligation named before work proceeds.</td>
</tr>
<tr class="even">
<td>1620</td>
<td><a href="#rune-1620">fail-fast</a></td>
<td>authored</td>
<td>reviewed</td>
<td>Abort early when assumptions break instead of smearing damage forward.</td>
</tr>
<tr class="odd">
<td>1621</td>
<td><a href="#rune-1621">first-class</a></td>
<td>authored</td>
<td>generated_draft</td>
<td><code>first-class</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the first-class obligation named before work proceeds.</td>
</tr>
<tr class="even">
<td>1622</td>
<td><a href="#rune-1622">hot path {Rune}</a></td>
<td>authored</td>
<td>generated_draft</td>
<td><code>hot path</code> in its Rune sense is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the hot path obligation named before work proceeds.</td>
</tr>
<tr class="odd">
<td>1623</td>
<td><a href="#rune-1623">infrastructure-as-code</a></td>
<td>authored</td>
<td>reviewed</td>
<td>Operational change expressed as reviewable source.</td>
</tr>
<tr class="even">
<td>1624</td>
<td><a href="#rune-1624">least-authority</a></td>
<td>authored</td>
<td>generated_draft</td>
<td><code>least-authority</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the least-authority obligation named before work proceeds.</td>
</tr>
<tr class="odd">
<td>1625</td>
<td><a href="#rune-1625">lock-free {Rune}</a></td>
<td>authored</td>
<td>generated_draft</td>
<td><code>lock-free</code> in its Rune sense is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the lock-free obligation named before work proceeds.</td>
</tr>
<tr class="even">
<td>1626</td>
<td><a href="#rune-1626">machine-readable</a></td>
<td>authored</td>
<td>reviewed</td>
<td>Structured so software, not only humans, can read it reliably.</td>
</tr>
<tr class="odd">
<td>1627</td>
<td><a href="#rune-1627">memory-safe {Rune}</a></td>
<td>authored</td>
<td>generated_draft</td>
<td><code>memory-safe</code> in its Rune sense is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the memory-safe obligation named before work proceeds.</td>
</tr>
<tr class="even">
<td>1628</td>
<td><a href="#rune-1628">multi-tenant</a></td>
<td>authored</td>
<td>generated_draft</td>
<td><code>multi-tenant</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the multi-tenant obligation named before work proceeds.</td>
</tr>
<tr class="odd">
<td>1629</td>
<td><a href="#rune-1629">negative cache</a></td>
<td>authored</td>
<td>generated_draft</td>
<td><code>negative cache</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the negative cache obligation named before work proceeds.</td>
</tr>
<tr class="even">
<td>1630</td>
<td><a href="#rune-1630">object-capability</a></td>
<td>authored</td>
<td>generated_draft</td>
<td><code>object-capability</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the object-capability obligation named before work proceeds.</td>
</tr>
<tr class="odd">
<td>1631</td>
<td><a href="#rune-1631">offline-first {Rune}</a></td>
<td>authored</td>
<td>reviewed</td>
<td>Designed to keep working with poor or absent connectivity.</td>
</tr>
<tr class="even">
<td>1632</td>
<td><a href="#rune-1632">policy-as-code</a></td>
<td>authored</td>
<td>reviewed</td>
<td>Policy declared as versioned, testable code.</td>
</tr>
<tr class="odd">
<td>1633</td>
<td><a href="#rune-1633">queue-backed</a></td>
<td>authored</td>
<td>generated_draft</td>
<td><code>queue-backed</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the queue-backed obligation named before work proceeds.</td>
</tr>
<tr class="even">
<td>1634</td>
<td><a href="#rune-1634">read path</a></td>
<td>authored</td>
<td>generated_draft</td>
<td><code>read path</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the read path obligation named before work proceeds.</td>
</tr>
<tr class="odd">
<td>1635</td>
<td><a href="#rune-1635">read-through cache</a></td>
<td>authored</td>
<td>generated_draft</td>
<td><code>read-through cache</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the read-through cache obligation named before work proceeds.</td>
</tr>
<tr class="even">
<td>1636</td>
<td><a href="#rune-1636">real-time {Rune}</a></td>
<td>authored</td>
<td>generated_draft</td>
<td><code>real-time</code> in its Rune sense is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the real-time obligation named before work proceeds.</td>
</tr>
<tr class="odd">
<td>1637</td>
<td><a href="#rune-1637">rule-based</a></td>
<td>authored</td>
<td>generated_draft</td>
<td><code>rule-based</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the rule-based obligation named before work proceeds.</td>
</tr>
<tr class="even">
<td>1638</td>
<td><a href="#rune-1638">side-effect-free {Rune}</a></td>
<td>authored</td>
<td>generated_draft</td>
<td><code>side-effect-free</code> in its Rune sense is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the side-effect-free obligation named before work proceeds.</td>
</tr>
<tr class="odd">
<td>1639</td>
<td><a href="#rune-1639">single source of truth</a></td>
<td>authored</td>
<td>reviewed</td>
<td>One canonical place others are expected to mirror.</td>
</tr>
<tr class="even">
<td>1640</td>
<td><a href="#rune-1640">soft delete</a></td>
<td>authored</td>
<td>generated_draft</td>
<td><code>soft delete</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the soft delete obligation named before work proceeds.</td>
</tr>
<tr class="odd">
<td>1641</td>
<td><a href="#rune-1641">statefulset</a></td>
<td>authored</td>
<td>generated_draft</td>
<td><code>statefulset</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the statefulset obligation named before work proceeds.</td>
</tr>
<tr class="even">
<td>1642</td>
<td><a href="#rune-1642">write path</a></td>
<td>authored</td>
<td>generated_draft</td>
<td><code>write path</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the write path obligation named before work proceeds.</td>
</tr>
<tr class="odd">
<td>1643</td>
<td><a href="#rune-1643">write-through cache</a></td>
<td>authored</td>
<td>generated_draft</td>
<td><code>write-through cache</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the write-through cache obligation named before work proceeds.</td>
</tr>
<tr class="even">
<td>1644</td>
<td><a href="#rune-1644">zero-downtime</a></td>
<td>authored</td>
<td>reviewed</td>
<td>Change introduced without taking the service dark.</td>
</tr>
<tr class="odd">
<td>1645</td>
<td><a href="#rune-1645">zero-knowledge</a></td>
<td>authored</td>
<td>generated_draft</td>
<td><code>zero-knowledge</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the zero-knowledge obligation named before work proceeds.</td>
</tr>
</tbody>
</table>
</section>
<section id="entries" class="level2" data-number="114.2">
<h2 data-number="114.2" class="anchored" data-anchor-id="entries"><span class="header-section-number">114.2</span> Entries</h2>
<section id="rune-1583" class="level3" data-number="114.2.1">
<h3 data-number="114.2.1" class="anchored" data-anchor-id="rune-1583"><span class="header-section-number">114.2.1</span> [1583] -able</h3>
<p><strong>Status:</strong> canonical</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> generated_draft</p>
<p><strong>Force:</strong> <code>-able</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the -able obligation named before work proceeds.</p>
<p><strong>Shadow:</strong> misusing <code>-able</code> at rune 1583 in the naming lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>-able</code> when the prompt needs this obligation made explicit: <code>-able</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the -able obligation named before work proceeds.</li>
<li>Ask the assistant to state the <code>-able</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>-able</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
</section>
<section id="rune-1584" class="level3" data-number="114.2.2">
<h3 data-number="114.2.2" class="anchored" data-anchor-id="rune-1584"><span class="header-section-number">114.2.2</span> [1584] -aware</h3>
<p><strong>Status:</strong> canonical (pocket canon)</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> reviewed</p>
<p><strong>Force:</strong> Marks that something notices the surrounding condition it names.</p>
<p><strong>Shadow:</strong> misusing <code>-aware</code> at rune 1584 in the naming lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>-aware</code> when the prompt needs this obligation made explicit: Marks that something notices the surrounding condition it names.</li>
<li>Ask the assistant to state the <code>-aware</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>-aware</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
<p><strong>Pocket gloss:</strong> Marks that something notices the surrounding condition it names.</p>
</section>
<section id="rune-1585" class="level3" data-number="114.2.3">
<h3 data-number="114.2.3" class="anchored" data-anchor-id="rune-1585"><span class="header-section-number">114.2.3</span> [1585] -by-design</h3>
<p><strong>Status:</strong> canonical</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> generated_draft</p>
<p><strong>Force:</strong> <code>-by-design</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the -by-design obligation named before work proceeds.</p>
<p><strong>Shadow:</strong> misusing <code>-by-design</code> at rune 1585 in the naming lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>-by-design</code> when the prompt needs this obligation made explicit: <code>-by-design</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the -by-design obligation named before work proceeds.</li>
<li>Ask the assistant to state the <code>-by-design</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>-by-design</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
</section>
<section id="rune-1586" class="level3" data-number="114.2.4">
<h3 data-number="114.2.4" class="anchored" data-anchor-id="rune-1586"><span class="header-section-number">114.2.4</span> [1586] -centric</h3>
<p><strong>Status:</strong> canonical</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> generated_draft</p>
<p><strong>Force:</strong> <code>-centric</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the -centric obligation named before work proceeds.</p>
<p><strong>Shadow:</strong> misusing <code>-centric</code> at rune 1586 in the naming lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>-centric</code> when the prompt needs this obligation made explicit: <code>-centric</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the -centric obligation named before work proceeds.</li>
<li>Ask the assistant to state the <code>-centric</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>-centric</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
</section>
<section id="rune-1587" class="level3" data-number="114.2.5">
<h3 data-number="114.2.5" class="anchored" data-anchor-id="rune-1587"><span class="header-section-number">114.2.5</span> [1587] -complete</h3>
<p><strong>Status:</strong> canonical</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> generated_draft</p>
<p><strong>Force:</strong> <code>-complete</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the -complete obligation named before work proceeds.</p>
<p><strong>Shadow:</strong> misusing <code>-complete</code> at rune 1587 in the naming lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>-complete</code> when the prompt needs this obligation made explicit: <code>-complete</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the -complete obligation named before work proceeds.</li>
<li>Ask the assistant to state the <code>-complete</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>-complete</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
</section>
<section id="rune-1588" class="level3" data-number="114.2.6">
<h3 data-number="114.2.6" class="anchored" data-anchor-id="rune-1588"><span class="header-section-number">114.2.6</span> [1588] -driven</h3>
<p><strong>Status:</strong> canonical (pocket canon)</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> reviewed</p>
<p><strong>Force:</strong> Signals that behavior is organized around events or causes.</p>
<p><strong>Shadow:</strong> misusing <code>-driven</code> at rune 1588 in the naming lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>-driven</code> when the prompt needs this obligation made explicit: Signals that behavior is organized around events or causes.</li>
<li>Ask the assistant to state the <code>-driven</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>-driven</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
<p><strong>Pocket gloss:</strong> Signals that behavior is organized around events or causes.</p>
</section>
<section id="rune-1589" class="level3" data-number="114.2.7">
<h3 data-number="114.2.7" class="anchored" data-anchor-id="rune-1589"><span class="header-section-number">114.2.7</span> [1589] -first</h3>
<p><strong>Status:</strong> canonical (pocket canon)</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> reviewed</p>
<p><strong>Force:</strong> Declares priority or design center: security-first, API-first, offline-first.</p>
<p><strong>Shadow:</strong> misusing <code>-first</code> at rune 1589 in the naming lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>-first</code> when the prompt needs this obligation made explicit: Declares priority or design center: security-first, API-first, offline-first.</li>
<li>Ask the assistant to state the <code>-first</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>-first</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
<p><strong>Pocket gloss:</strong> Declares priority or design center: security-first, API-first, offline-first.</p>
</section>
<section id="rune-1590" class="level3" data-number="114.2.8">
<h3 data-number="114.2.8" class="anchored" data-anchor-id="rune-1590"><span class="header-section-number">114.2.8</span> [1590] -free</h3>
<p><strong>Status:</strong> canonical</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> generated_draft</p>
<p><strong>Force:</strong> <code>-free</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the -free obligation named before work proceeds.</p>
<p><strong>Shadow:</strong> misusing <code>-free</code> at rune 1590 in the naming lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>-free</code> when the prompt needs this obligation made explicit: <code>-free</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the -free obligation named before work proceeds.</li>
<li>Ask the assistant to state the <code>-free</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>-free</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
</section>
<section id="rune-1591" class="level3" data-number="114.2.9">
<h3 data-number="114.2.9" class="anchored" data-anchor-id="rune-1591"><span class="header-section-number">114.2.9</span> [1591] -friendly</h3>
<p><strong>Status:</strong> canonical</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> generated_draft</p>
<p><strong>Force:</strong> <code>-friendly</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the -friendly obligation named before work proceeds.</p>
<p><strong>Shadow:</strong> misusing <code>-friendly</code> at rune 1591 in the naming lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>-friendly</code> when the prompt needs this obligation made explicit: <code>-friendly</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the -friendly obligation named before work proceeds.</li>
<li>Ask the assistant to state the <code>-friendly</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>-friendly</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
</section>
<section id="rune-1592" class="level3" data-number="114.2.10">
<h3 data-number="114.2.10" class="anchored" data-anchor-id="rune-1592"><span class="header-section-number">114.2.10</span> [1592] -hard</h3>
<p><strong>Status:</strong> canonical</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> generated_draft</p>
<p><strong>Force:</strong> <code>-hard</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the -hard obligation named before work proceeds.</p>
<p><strong>Shadow:</strong> misusing <code>-hard</code> at rune 1592 in the naming lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>-hard</code> when the prompt needs this obligation made explicit: <code>-hard</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the -hard obligation named before work proceeds.</li>
<li>Ask the assistant to state the <code>-hard</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>-hard</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
</section>
<section id="rune-1593" class="level3" data-number="114.2.11">
<h3 data-number="114.2.11" class="anchored" data-anchor-id="rune-1593"><span class="header-section-number">114.2.11</span> [1593] -less</h3>
<p><strong>Status:</strong> canonical</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> generated_draft</p>
<p><strong>Force:</strong> <code>-less</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the -less obligation named before work proceeds.</p>
<p><strong>Shadow:</strong> misusing <code>-less</code> at rune 1593 in the naming lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>-less</code> when the prompt needs this obligation made explicit: <code>-less</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the -less obligation named before work proceeds.</li>
<li>Ask the assistant to state the <code>-less</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>-less</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
</section>
<section id="rune-1594" class="level3" data-number="114.2.12">
<h3 data-number="114.2.12" class="anchored" data-anchor-id="rune-1594"><span class="header-section-number">114.2.12</span> [1594] -local</h3>
<p><strong>Status:</strong> canonical</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> generated_draft</p>
<p><strong>Force:</strong> <code>-local</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the -local obligation named before work proceeds.</p>
<p><strong>Shadow:</strong> misusing <code>-local</code> at rune 1594 in the naming lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>-local</code> when the prompt needs this obligation made explicit: <code>-local</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the -local obligation named before work proceeds.</li>
<li>Ask the assistant to state the <code>-local</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>-local</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
</section>
<section id="rune-1595" class="level3" data-number="114.2.13">
<h3 data-number="114.2.13" class="anchored" data-anchor-id="rune-1595"><span class="header-section-number">114.2.13</span> [1595] -native</h3>
<p><strong>Status:</strong> canonical</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> generated_draft</p>
<p><strong>Force:</strong> <code>-native</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the -native obligation named before work proceeds.</p>
<p><strong>Shadow:</strong> misusing <code>-native</code> at rune 1595 in the naming lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>-native</code> when the prompt needs this obligation made explicit: <code>-native</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the -native obligation named before work proceeds.</li>
<li>Ask the assistant to state the <code>-native</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>-native</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
</section>
<section id="rune-1596" class="level3" data-number="114.2.14">
<h3 data-number="114.2.14" class="anchored" data-anchor-id="rune-1596"><span class="header-section-number">114.2.14</span> [1596] -of-record</h3>
<p><strong>Status:</strong> canonical</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> generated_draft</p>
<p><strong>Force:</strong> <code>-of-record</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the -of-record obligation named before work proceeds.</p>
<p><strong>Shadow:</strong> misusing <code>-of-record</code> at rune 1596 in the naming lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>-of-record</code> when the prompt needs this obligation made explicit: <code>-of-record</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the -of-record obligation named before work proceeds.</li>
<li>Ask the assistant to state the <code>-of-record</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>-of-record</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
</section>
<section id="rune-1597" class="level3" data-number="114.2.15">
<h3 data-number="114.2.15" class="anchored" data-anchor-id="rune-1597"><span class="header-section-number">114.2.15</span> [1597] -oriented</h3>
<p><strong>Status:</strong> canonical</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> generated_draft</p>
<p><strong>Force:</strong> <code>-oriented</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the -oriented obligation named before work proceeds.</p>
<p><strong>Shadow:</strong> misusing <code>-oriented</code> at rune 1597 in the naming lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>-oriented</code> when the prompt needs this obligation made explicit: <code>-oriented</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the -oriented obligation named before work proceeds.</li>
<li>Ask the assistant to state the <code>-oriented</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>-oriented</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
</section>
<section id="rune-1598" class="level3" data-number="114.2.16">
<h3 data-number="114.2.16" class="anchored" data-anchor-id="rune-1598"><span class="header-section-number">114.2.16</span> [1598] -safe</h3>
<p><strong>Status:</strong> canonical (pocket canon)</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> reviewed</p>
<p><strong>Force:</strong> Asserts a protected behavior such as memory-safe or thread-safe.</p>
<p><strong>Shadow:</strong> misusing <code>-safe</code> at rune 1598 in the naming lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>-safe</code> when the prompt needs this obligation made explicit: Asserts a protected behavior such as memory-safe or thread-safe.</li>
<li>Ask the assistant to state the <code>-safe</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>-safe</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
<p><strong>Pocket gloss:</strong> Asserts a protected behavior such as memory-safe or thread-safe.</p>
</section>
<section id="rune-1599" class="level3" data-number="114.2.17">
<h3 data-number="114.2.17" class="anchored" data-anchor-id="rune-1599"><span class="header-section-number">114.2.17</span> [1599] -sensitive</h3>
<p><strong>Status:</strong> canonical</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> generated_draft</p>
<p><strong>Force:</strong> <code>-sensitive</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the -sensitive obligation named before work proceeds.</p>
<p><strong>Shadow:</strong> misusing <code>-sensitive</code> at rune 1599 in the naming lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>-sensitive</code> when the prompt needs this obligation made explicit: <code>-sensitive</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the -sensitive obligation named before work proceeds.</li>
<li>Ask the assistant to state the <code>-sensitive</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>-sensitive</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
</section>
<section id="rune-1600" class="level3" data-number="114.2.18">
<h3 data-number="114.2.18" class="anchored" data-anchor-id="rune-1600"><span class="header-section-number">114.2.18</span> [1600] -shaped</h3>
<p><strong>Status:</strong> canonical</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> generated_draft</p>
<p><strong>Force:</strong> <code>-shaped</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the -shaped obligation named before work proceeds.</p>
<p><strong>Shadow:</strong> misusing <code>-shaped</code> at rune 1600 in the naming lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>-shaped</code> when the prompt needs this obligation made explicit: <code>-shaped</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the -shaped obligation named before work proceeds.</li>
<li>Ask the assistant to state the <code>-shaped</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>-shaped</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
</section>
<section id="rune-1601" class="level3" data-number="114.2.19">
<h3 data-number="114.2.19" class="anchored" data-anchor-id="rune-1601"><span class="header-section-number">114.2.19</span> [1601] -soft</h3>
<p><strong>Status:</strong> canonical</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> generated_draft</p>
<p><strong>Force:</strong> <code>-soft</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the -soft obligation named before work proceeds.</p>
<p><strong>Shadow:</strong> misusing <code>-soft</code> at rune 1601 in the naming lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>-soft</code> when the prompt needs this obligation made explicit: <code>-soft</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the -soft obligation named before work proceeds.</li>
<li>Ask the assistant to state the <code>-soft</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>-soft</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
</section>
<section id="rune-1602" class="level3" data-number="114.2.20">
<h3 data-number="114.2.20" class="anchored" data-anchor-id="rune-1602"><span class="header-section-number">114.2.20</span> [1602] -tolerant</h3>
<p><strong>Status:</strong> canonical</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> generated_draft</p>
<p><strong>Force:</strong> <code>-tolerant</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the -tolerant obligation named before work proceeds.</p>
<p><strong>Shadow:</strong> misusing <code>-tolerant</code> at rune 1602 in the naming lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>-tolerant</code> when the prompt needs this obligation made explicit: <code>-tolerant</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the -tolerant obligation named before work proceeds.</li>
<li>Ask the assistant to state the <code>-tolerant</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>-tolerant</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
</section>
<section id="rune-1603" class="level3" data-number="114.2.21">
<h3 data-number="114.2.21" class="anchored" data-anchor-id="rune-1603"><span class="header-section-number">114.2.21</span> [1603] -wide</h3>
<p><strong>Status:</strong> canonical</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> generated_draft</p>
<p><strong>Force:</strong> <code>-wide</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the -wide obligation named before work proceeds.</p>
<p><strong>Shadow:</strong> misusing <code>-wide</code> at rune 1603 in the naming lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>-wide</code> when the prompt needs this obligation made explicit: <code>-wide</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the -wide obligation named before work proceeds.</li>
<li>Ask the assistant to state the <code>-wide</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>-wide</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
</section>
<section id="rune-1604" class="level3" data-number="114.2.22">
<h3 data-number="114.2.22" class="anchored" data-anchor-id="rune-1604"><span class="header-section-number">114.2.22</span> [1604] actor model</h3>
<p><strong>Status:</strong> canonical</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> generated_draft</p>
<p><strong>Force:</strong> <code>actor model</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the actor model obligation named before work proceeds.</p>
<p><strong>Shadow:</strong> misusing <code>actor model</code> at rune 1604 in the naming lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>actor model</code> when the prompt needs this obligation made explicit: <code>actor model</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the actor model obligation named before work proceeds.</li>
<li>Ask the assistant to state the <code>actor model</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>actor model</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
</section>
<section id="rune-1605" class="level3" data-number="114.2.23">
<h3 data-number="114.2.23" class="anchored" data-anchor-id="rune-1605"><span class="header-section-number">114.2.23</span> [1605] API-first</h3>
<p><strong>Status:</strong> canonical (pocket canon)</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> reviewed</p>
<p><strong>Force:</strong> Design the interface surface before the implementations behind it.</p>
<p><strong>Shadow:</strong> misusing <code>API-first</code> at rune 1605 in the naming lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>API-first</code> when the prompt needs this obligation made explicit: Design the interface surface before the implementations behind it.</li>
<li>Ask the assistant to state the <code>API-first</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>API-first</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
<p><strong>Pocket gloss:</strong> Design the interface surface before the implementations behind it.</p>
</section>
<section id="rune-1606" class="level3" data-number="114.2.24">
<h3 data-number="114.2.24" class="anchored" data-anchor-id="rune-1606"><span class="header-section-number">114.2.24</span> [1606] append-only</h3>
<p><strong>Status:</strong> canonical (pocket canon)</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> reviewed</p>
<p><strong>Force:</strong> History grows by addition rather than mutation.</p>
<p><strong>Shadow:</strong> misusing <code>append-only</code> at rune 1606 in the naming lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>append-only</code> when the prompt needs this obligation made explicit: History grows by addition rather than mutation.</li>
<li>Ask the assistant to state the <code>append-only</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>append-only</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
<p><strong>Pocket gloss:</strong> History grows by addition rather than mutation.</p>
</section>
<section id="rune-1607" class="level3" data-number="114.2.25">
<h3 data-number="114.2.25" class="anchored" data-anchor-id="rune-1607"><span class="header-section-number">114.2.25</span> [1607] best-effort</h3>
<p><strong>Status:</strong> canonical</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> generated_draft</p>
<p><strong>Force:</strong> <code>best-effort</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the best-effort obligation named before work proceeds.</p>
<p><strong>Shadow:</strong> misusing <code>best-effort</code> at rune 1607 in the naming lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>best-effort</code> when the prompt needs this obligation made explicit: <code>best-effort</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the best-effort obligation named before work proceeds.</li>
<li>Ask the assistant to state the <code>best-effort</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>best-effort</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
</section>
<section id="rune-1608" class="level3" data-number="114.2.26">
<h3 data-number="114.2.26" class="anchored" data-anchor-id="rune-1608"><span class="header-section-number">114.2.26</span> [1608] branch-free</h3>
<p><strong>Status:</strong> canonical</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> generated_draft</p>
<p><strong>Force:</strong> <code>branch-free</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the branch-free obligation named before work proceeds.</p>
<p><strong>Shadow:</strong> misusing <code>branch-free</code> at rune 1608 in the naming lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>branch-free</code> when the prompt needs this obligation made explicit: <code>branch-free</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the branch-free obligation named before work proceeds.</li>
<li>Ask the assistant to state the <code>branch-free</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>branch-free</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
</section>
<section id="rune-1609" class="level3" data-number="114.2.27">
<h3 data-number="114.2.27" class="anchored" data-anchor-id="rune-1609"><span class="header-section-number">114.2.27</span> [1609] cloud-native</h3>
<p><strong>Status:</strong> canonical</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> generated_draft</p>
<p><strong>Force:</strong> <code>cloud-native</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the cloud-native obligation named before work proceeds.</p>
<p><strong>Shadow:</strong> misusing <code>cloud-native</code> at rune 1609 in the naming lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>cloud-native</code> when the prompt needs this obligation made explicit: <code>cloud-native</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the cloud-native obligation named before work proceeds.</li>
<li>Ask the assistant to state the <code>cloud-native</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>cloud-native</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
</section>
<section id="rune-1610" class="level3" data-number="114.2.28">
<h3 data-number="114.2.28" class="anchored" data-anchor-id="rune-1610"><span class="header-section-number">114.2.28</span> [1610] command-query</h3>
<p><strong>Status:</strong> canonical</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> generated_draft</p>
<p><strong>Force:</strong> <code>command-query</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the command-query obligation named before work proceeds.</p>
<p><strong>Shadow:</strong> misusing <code>command-query</code> at rune 1610 in the naming lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>command-query</code> when the prompt needs this obligation made explicit: <code>command-query</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the command-query obligation named before work proceeds.</li>
<li>Ask the assistant to state the <code>command-query</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>command-query</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
</section>
<section id="rune-1611" class="level3" data-number="114.2.29">
<h3 data-number="114.2.29" class="anchored" data-anchor-id="rune-1611"><span class="header-section-number">114.2.29</span> [1611] control plane {Rune}</h3>
<p><strong>Status:</strong> canonical</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> generated_draft</p>
<p><strong>Force:</strong> <code>control plane</code> in its Rune sense is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the control plane obligation named before work proceeds.</p>
<p><strong>Shadow:</strong> misusing <code>control plane</code> at rune 1611 in the Rune lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>control plane</code> when the prompt needs this obligation made explicit: <code>control plane</code> in its Rune sense is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the control plane obligation named before work proceeds.</li>
<li>Ask the assistant to state the <code>control plane</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>control plane</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
</section>
<section id="rune-1612" class="level3" data-number="114.2.30">
<h3 data-number="114.2.30" class="anchored" data-anchor-id="rune-1612"><span class="header-section-number">114.2.30</span> [1612] copy-on-write {Rune}</h3>
<p><strong>Status:</strong> canonical</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> generated_draft</p>
<p><strong>Force:</strong> <code>copy-on-write</code> in its Rune sense is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the copy-on-write obligation named before work proceeds.</p>
<p><strong>Shadow:</strong> misusing <code>copy-on-write</code> at rune 1612 in the Rune lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>copy-on-write</code> when the prompt needs this obligation made explicit: <code>copy-on-write</code> in its Rune sense is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the copy-on-write obligation named before work proceeds.</li>
<li>Ask the assistant to state the <code>copy-on-write</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>copy-on-write</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
</section>
<section id="rune-1613" class="level3" data-number="114.2.31">
<h3 data-number="114.2.31" class="anchored" data-anchor-id="rune-1613"><span class="header-section-number">114.2.31</span> [1613] crash-only</h3>
<p><strong>Status:</strong> canonical (pocket canon)</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> reviewed</p>
<p><strong>Force:</strong> Only live briefly, start fast, and recover by restart rather than repair.</p>
<p><strong>Shadow:</strong> misusing <code>crash-only</code> at rune 1613 in the naming lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>crash-only</code> when the prompt needs this obligation made explicit: Only live briefly, start fast, and recover by restart rather than repair.</li>
<li>Ask the assistant to state the <code>crash-only</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>crash-only</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
<p><strong>Pocket gloss:</strong> Only live briefly, start fast, and recover by restart rather than repair.</p>
</section>
<section id="rune-1614" class="level3" data-number="114.2.32">
<h3 data-number="114.2.32" class="anchored" data-anchor-id="rune-1614"><span class="header-section-number">114.2.32</span> [1614] data plane {Rune}</h3>
<p><strong>Status:</strong> canonical</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> generated_draft</p>
<p><strong>Force:</strong> <code>data plane</code> in its Rune sense is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the data plane obligation named before work proceeds.</p>
<p><strong>Shadow:</strong> misusing <code>data plane</code> at rune 1614 in the Rune lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>data plane</code> when the prompt needs this obligation made explicit: <code>data plane</code> in its Rune sense is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the data plane obligation named before work proceeds.</li>
<li>Ask the assistant to state the <code>data plane</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>data plane</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
</section>
<section id="rune-1615" class="level3" data-number="114.2.33">
<h3 data-number="114.2.33" class="anchored" data-anchor-id="rune-1615"><span class="header-section-number">114.2.33</span> [1615] data-driven</h3>
<p><strong>Status:</strong> canonical</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> generated_draft</p>
<p><strong>Force:</strong> <code>data-driven</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the data-driven obligation named before work proceeds.</p>
<p><strong>Shadow:</strong> misusing <code>data-driven</code> at rune 1615 in the naming lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>data-driven</code> when the prompt needs this obligation made explicit: <code>data-driven</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the data-driven obligation named before work proceeds.</li>
<li>Ask the assistant to state the <code>data-driven</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>data-driven</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
</section>
<section id="rune-1616" class="level3" data-number="114.2.34">
<h3 data-number="114.2.34" class="anchored" data-anchor-id="rune-1616"><span class="header-section-number">114.2.34</span> [1616] default-deny</h3>
<p><strong>Status:</strong> canonical (pocket canon)</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> reviewed</p>
<p><strong>Force:</strong> Access is forbidden unless explicitly granted.</p>
<p><strong>Shadow:</strong> misusing <code>default-deny</code> at rune 1616 in the naming lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>default-deny</code> when the prompt needs this obligation made explicit: Access is forbidden unless explicitly granted.</li>
<li>Ask the assistant to state the <code>default-deny</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>default-deny</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
<p><strong>Pocket gloss:</strong> Access is forbidden unless explicitly granted.</p>
</section>
<section id="rune-1617" class="level3" data-number="114.2.35">
<h3 data-number="114.2.35" class="anchored" data-anchor-id="rune-1617"><span class="header-section-number">114.2.35</span> [1617] edge-native</h3>
<p><strong>Status:</strong> canonical</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> generated_draft</p>
<p><strong>Force:</strong> <code>edge-native</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the edge-native obligation named before work proceeds.</p>
<p><strong>Shadow:</strong> misusing <code>edge-native</code> at rune 1617 in the naming lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>edge-native</code> when the prompt needs this obligation made explicit: <code>edge-native</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the edge-native obligation named before work proceeds.</li>
<li>Ask the assistant to state the <code>edge-native</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>edge-native</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
</section>
<section id="rune-1618" class="level3" data-number="114.2.36">
<h3 data-number="114.2.36" class="anchored" data-anchor-id="rune-1618"><span class="header-section-number">114.2.36</span> [1618] event-driven</h3>
<p><strong>Status:</strong> canonical (pocket canon)</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> reviewed</p>
<p><strong>Force:</strong> Action propagates from events rather than from direct polling or command loops.</p>
<p><strong>Shadow:</strong> misusing <code>event-driven</code> at rune 1618 in the naming lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>event-driven</code> when the prompt needs this obligation made explicit: Action propagates from events rather than from direct polling or command loops.</li>
<li>Ask the assistant to state the <code>event-driven</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>event-driven</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
<p><strong>Pocket gloss:</strong> Action propagates from events rather than from direct polling or command loops.</p>
</section>
<section id="rune-1619" class="level3" data-number="114.2.37">
<h3 data-number="114.2.37" class="anchored" data-anchor-id="rune-1619"><span class="header-section-number">114.2.37</span> [1619] eventually consistent</h3>
<p><strong>Status:</strong> canonical</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> generated_draft</p>
<p><strong>Force:</strong> <code>eventually consistent</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the eventually consistent obligation named before work proceeds.</p>
<p><strong>Shadow:</strong> misusing <code>eventually consistent</code> at rune 1619 in the naming lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>eventually consistent</code> when the prompt needs this obligation made explicit: <code>eventually consistent</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the eventually consistent obligation named before work proceeds.</li>
<li>Ask the assistant to state the <code>eventually consistent</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>eventually consistent</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
</section>
<section id="rune-1620" class="level3" data-number="114.2.38">
<h3 data-number="114.2.38" class="anchored" data-anchor-id="rune-1620"><span class="header-section-number">114.2.38</span> [1620] fail-fast</h3>
<p><strong>Status:</strong> canonical (pocket canon)</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> reviewed</p>
<p><strong>Force:</strong> Abort early when assumptions break instead of smearing damage forward.</p>
<p><strong>Shadow:</strong> misusing <code>fail-fast</code> at rune 1620 in the naming lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>fail-fast</code> when the prompt needs this obligation made explicit: Abort early when assumptions break instead of smearing damage forward.</li>
<li>Ask the assistant to state the <code>fail-fast</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>fail-fast</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
<p><strong>Pocket gloss:</strong> Abort early when assumptions break instead of smearing damage forward.</p>
</section>
<section id="rune-1621" class="level3" data-number="114.2.39">
<h3 data-number="114.2.39" class="anchored" data-anchor-id="rune-1621"><span class="header-section-number">114.2.39</span> [1621] first-class</h3>
<p><strong>Status:</strong> canonical</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> generated_draft</p>
<p><strong>Force:</strong> <code>first-class</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the first-class obligation named before work proceeds.</p>
<p><strong>Shadow:</strong> misusing <code>first-class</code> at rune 1621 in the naming lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>first-class</code> when the prompt needs this obligation made explicit: <code>first-class</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the first-class obligation named before work proceeds.</li>
<li>Ask the assistant to state the <code>first-class</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>first-class</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
</section>
<section id="rune-1622" class="level3" data-number="114.2.40">
<h3 data-number="114.2.40" class="anchored" data-anchor-id="rune-1622"><span class="header-section-number">114.2.40</span> [1622] hot path {Rune}</h3>
<p><strong>Status:</strong> canonical</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> generated_draft</p>
<p><strong>Force:</strong> <code>hot path</code> in its Rune sense is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the hot path obligation named before work proceeds.</p>
<p><strong>Shadow:</strong> misusing <code>hot path</code> at rune 1622 in the Rune lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>hot path</code> when the prompt needs this obligation made explicit: <code>hot path</code> in its Rune sense is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the hot path obligation named before work proceeds.</li>
<li>Ask the assistant to state the <code>hot path</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>hot path</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
</section>
<section id="rune-1623" class="level3" data-number="114.2.41">
<h3 data-number="114.2.41" class="anchored" data-anchor-id="rune-1623"><span class="header-section-number">114.2.41</span> [1623] infrastructure-as-code</h3>
<p><strong>Status:</strong> canonical (pocket canon)</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> reviewed</p>
<p><strong>Force:</strong> Operational change expressed as reviewable source.</p>
<p><strong>Shadow:</strong> misusing <code>infrastructure-as-code</code> at rune 1623 in the naming lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>infrastructure-as-code</code> when the prompt needs this obligation made explicit: Operational change expressed as reviewable source.</li>
<li>Ask the assistant to state the <code>infrastructure-as-code</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>infrastructure-as-code</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
<p><strong>Pocket gloss:</strong> Operational change expressed as reviewable source.</p>
</section>
<section id="rune-1624" class="level3" data-number="114.2.42">
<h3 data-number="114.2.42" class="anchored" data-anchor-id="rune-1624"><span class="header-section-number">114.2.42</span> [1624] least-authority</h3>
<p><strong>Status:</strong> canonical</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> generated_draft</p>
<p><strong>Force:</strong> <code>least-authority</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the least-authority obligation named before work proceeds.</p>
<p><strong>Shadow:</strong> misusing <code>least-authority</code> at rune 1624 in the naming lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>least-authority</code> when the prompt needs this obligation made explicit: <code>least-authority</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the least-authority obligation named before work proceeds.</li>
<li>Ask the assistant to state the <code>least-authority</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>least-authority</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
</section>
<section id="rune-1625" class="level3" data-number="114.2.43">
<h3 data-number="114.2.43" class="anchored" data-anchor-id="rune-1625"><span class="header-section-number">114.2.43</span> [1625] lock-free {Rune}</h3>
<p><strong>Status:</strong> canonical</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> generated_draft</p>
<p><strong>Force:</strong> <code>lock-free</code> in its Rune sense is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the lock-free obligation named before work proceeds.</p>
<p><strong>Shadow:</strong> misusing <code>lock-free</code> at rune 1625 in the Rune lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>lock-free</code> when the prompt needs this obligation made explicit: <code>lock-free</code> in its Rune sense is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the lock-free obligation named before work proceeds.</li>
<li>Ask the assistant to state the <code>lock-free</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>lock-free</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
</section>
<section id="rune-1626" class="level3" data-number="114.2.44">
<h3 data-number="114.2.44" class="anchored" data-anchor-id="rune-1626"><span class="header-section-number">114.2.44</span> [1626] machine-readable</h3>
<p><strong>Status:</strong> canonical (pocket canon)</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> reviewed</p>
<p><strong>Force:</strong> Structured so software, not only humans, can read it reliably.</p>
<p><strong>Shadow:</strong> misusing <code>machine-readable</code> at rune 1626 in the naming lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>machine-readable</code> when the prompt needs this obligation made explicit: Structured so software, not only humans, can read it reliably.</li>
<li>Ask the assistant to state the <code>machine-readable</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>machine-readable</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
<p><strong>Pocket gloss:</strong> Structured so software, not only humans, can read it reliably.</p>
</section>
<section id="rune-1627" class="level3" data-number="114.2.45">
<h3 data-number="114.2.45" class="anchored" data-anchor-id="rune-1627"><span class="header-section-number">114.2.45</span> [1627] memory-safe {Rune}</h3>
<p><strong>Status:</strong> canonical</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> generated_draft</p>
<p><strong>Force:</strong> <code>memory-safe</code> in its Rune sense is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the memory-safe obligation named before work proceeds.</p>
<p><strong>Shadow:</strong> misusing <code>memory-safe</code> at rune 1627 in the Rune lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>memory-safe</code> when the prompt needs this obligation made explicit: <code>memory-safe</code> in its Rune sense is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the memory-safe obligation named before work proceeds.</li>
<li>Ask the assistant to state the <code>memory-safe</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>memory-safe</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
</section>
<section id="rune-1628" class="level3" data-number="114.2.46">
<h3 data-number="114.2.46" class="anchored" data-anchor-id="rune-1628"><span class="header-section-number">114.2.46</span> [1628] multi-tenant</h3>
<p><strong>Status:</strong> canonical</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> generated_draft</p>
<p><strong>Force:</strong> <code>multi-tenant</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the multi-tenant obligation named before work proceeds.</p>
<p><strong>Shadow:</strong> misusing <code>multi-tenant</code> at rune 1628 in the naming lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>multi-tenant</code> when the prompt needs this obligation made explicit: <code>multi-tenant</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the multi-tenant obligation named before work proceeds.</li>
<li>Ask the assistant to state the <code>multi-tenant</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>multi-tenant</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
</section>
<section id="rune-1629" class="level3" data-number="114.2.47">
<h3 data-number="114.2.47" class="anchored" data-anchor-id="rune-1629"><span class="header-section-number">114.2.47</span> [1629] negative cache</h3>
<p><strong>Status:</strong> canonical</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> generated_draft</p>
<p><strong>Force:</strong> <code>negative cache</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the negative cache obligation named before work proceeds.</p>
<p><strong>Shadow:</strong> misusing <code>negative cache</code> at rune 1629 in the naming lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>negative cache</code> when the prompt needs this obligation made explicit: <code>negative cache</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the negative cache obligation named before work proceeds.</li>
<li>Ask the assistant to state the <code>negative cache</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>negative cache</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
</section>
<section id="rune-1630" class="level3" data-number="114.2.48">
<h3 data-number="114.2.48" class="anchored" data-anchor-id="rune-1630"><span class="header-section-number">114.2.48</span> [1630] object-capability</h3>
<p><strong>Status:</strong> canonical</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> generated_draft</p>
<p><strong>Force:</strong> <code>object-capability</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the object-capability obligation named before work proceeds.</p>
<p><strong>Shadow:</strong> misusing <code>object-capability</code> at rune 1630 in the naming lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>object-capability</code> when the prompt needs this obligation made explicit: <code>object-capability</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the object-capability obligation named before work proceeds.</li>
<li>Ask the assistant to state the <code>object-capability</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>object-capability</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
</section>
<section id="rune-1631" class="level3" data-number="114.2.49">
<h3 data-number="114.2.49" class="anchored" data-anchor-id="rune-1631"><span class="header-section-number">114.2.49</span> [1631] offline-first {Rune}</h3>
<p><strong>Status:</strong> canonical (pocket canon)</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> reviewed</p>
<p><strong>Force:</strong> Designed to keep working with poor or absent connectivity.</p>
<p><strong>Shadow:</strong> misusing <code>offline-first</code> at rune 1631 in the Rune lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>offline-first</code> when the prompt needs this obligation made explicit: Designed to keep working with poor or absent connectivity.</li>
<li>Ask the assistant to state the <code>offline-first</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>offline-first</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
<p><strong>Pocket gloss:</strong> Designed to keep working with poor or absent connectivity.</p>
</section>
<section id="rune-1632" class="level3" data-number="114.2.50">
<h3 data-number="114.2.50" class="anchored" data-anchor-id="rune-1632"><span class="header-section-number">114.2.50</span> [1632] policy-as-code</h3>
<p><strong>Status:</strong> canonical (pocket canon)</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> reviewed</p>
<p><strong>Force:</strong> Policy declared as versioned, testable code.</p>
<p><strong>Shadow:</strong> misusing <code>policy-as-code</code> at rune 1632 in the naming lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>policy-as-code</code> when the prompt needs this obligation made explicit: Policy declared as versioned, testable code.</li>
<li>Ask the assistant to state the <code>policy-as-code</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>policy-as-code</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
<p><strong>Pocket gloss:</strong> Policy declared as versioned, testable code.</p>
</section>
<section id="rune-1633" class="level3" data-number="114.2.51">
<h3 data-number="114.2.51" class="anchored" data-anchor-id="rune-1633"><span class="header-section-number">114.2.51</span> [1633] queue-backed</h3>
<p><strong>Status:</strong> canonical</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> generated_draft</p>
<p><strong>Force:</strong> <code>queue-backed</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the queue-backed obligation named before work proceeds.</p>
<p><strong>Shadow:</strong> misusing <code>queue-backed</code> at rune 1633 in the naming lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>queue-backed</code> when the prompt needs this obligation made explicit: <code>queue-backed</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the queue-backed obligation named before work proceeds.</li>
<li>Ask the assistant to state the <code>queue-backed</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>queue-backed</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
</section>
<section id="rune-1634" class="level3" data-number="114.2.52">
<h3 data-number="114.2.52" class="anchored" data-anchor-id="rune-1634"><span class="header-section-number">114.2.52</span> [1634] read path</h3>
<p><strong>Status:</strong> canonical</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> generated_draft</p>
<p><strong>Force:</strong> <code>read path</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the read path obligation named before work proceeds.</p>
<p><strong>Shadow:</strong> misusing <code>read path</code> at rune 1634 in the naming lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>read path</code> when the prompt needs this obligation made explicit: <code>read path</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the read path obligation named before work proceeds.</li>
<li>Ask the assistant to state the <code>read path</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>read path</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
</section>
<section id="rune-1635" class="level3" data-number="114.2.53">
<h3 data-number="114.2.53" class="anchored" data-anchor-id="rune-1635"><span class="header-section-number">114.2.53</span> [1635] read-through cache</h3>
<p><strong>Status:</strong> canonical</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> generated_draft</p>
<p><strong>Force:</strong> <code>read-through cache</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the read-through cache obligation named before work proceeds.</p>
<p><strong>Shadow:</strong> misusing <code>read-through cache</code> at rune 1635 in the naming lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>read-through cache</code> when the prompt needs this obligation made explicit: <code>read-through cache</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the read-through cache obligation named before work proceeds.</li>
<li>Ask the assistant to state the <code>read-through cache</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>read-through cache</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
</section>
<section id="rune-1636" class="level3" data-number="114.2.54">
<h3 data-number="114.2.54" class="anchored" data-anchor-id="rune-1636"><span class="header-section-number">114.2.54</span> [1636] real-time {Rune}</h3>
<p><strong>Status:</strong> canonical</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> generated_draft</p>
<p><strong>Force:</strong> <code>real-time</code> in its Rune sense is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the real-time obligation named before work proceeds.</p>
<p><strong>Shadow:</strong> misusing <code>real-time</code> at rune 1636 in the Rune lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>real-time</code> when the prompt needs this obligation made explicit: <code>real-time</code> in its Rune sense is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the real-time obligation named before work proceeds.</li>
<li>Ask the assistant to state the <code>real-time</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>real-time</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
</section>
<section id="rune-1637" class="level3" data-number="114.2.55">
<h3 data-number="114.2.55" class="anchored" data-anchor-id="rune-1637"><span class="header-section-number">114.2.55</span> [1637] rule-based</h3>
<p><strong>Status:</strong> canonical</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> generated_draft</p>
<p><strong>Force:</strong> <code>rule-based</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the rule-based obligation named before work proceeds.</p>
<p><strong>Shadow:</strong> misusing <code>rule-based</code> at rune 1637 in the naming lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>rule-based</code> when the prompt needs this obligation made explicit: <code>rule-based</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the rule-based obligation named before work proceeds.</li>
<li>Ask the assistant to state the <code>rule-based</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>rule-based</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
</section>
<section id="rune-1638" class="level3" data-number="114.2.56">
<h3 data-number="114.2.56" class="anchored" data-anchor-id="rune-1638"><span class="header-section-number">114.2.56</span> [1638] side-effect-free {Rune}</h3>
<p><strong>Status:</strong> canonical</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> generated_draft</p>
<p><strong>Force:</strong> <code>side-effect-free</code> in its Rune sense is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the side-effect-free obligation named before work proceeds.</p>
<p><strong>Shadow:</strong> misusing <code>side-effect-free</code> at rune 1638 in the Rune lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>side-effect-free</code> when the prompt needs this obligation made explicit: <code>side-effect-free</code> in its Rune sense is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the side-effect-free obligation named before work proceeds.</li>
<li>Ask the assistant to state the <code>side-effect-free</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>side-effect-free</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
</section>
<section id="rune-1639" class="level3" data-number="114.2.57">
<h3 data-number="114.2.57" class="anchored" data-anchor-id="rune-1639"><span class="header-section-number">114.2.57</span> [1639] single source of truth</h3>
<p><strong>Status:</strong> canonical (pocket canon)</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> reviewed</p>
<p><strong>Force:</strong> One canonical place others are expected to mirror.</p>
<p><strong>Shadow:</strong> misusing <code>single source of truth</code> at rune 1639 in the naming lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>single source of truth</code> when the prompt needs this obligation made explicit: One canonical place others are expected to mirror.</li>
<li>Ask the assistant to state the <code>single source of truth</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>single source of truth</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
<p><strong>Pocket gloss:</strong> One canonical place others are expected to mirror.</p>
</section>
<section id="rune-1640" class="level3" data-number="114.2.58">
<h3 data-number="114.2.58" class="anchored" data-anchor-id="rune-1640"><span class="header-section-number">114.2.58</span> [1640] soft delete</h3>
<p><strong>Status:</strong> canonical</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> generated_draft</p>
<p><strong>Force:</strong> <code>soft delete</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the soft delete obligation named before work proceeds.</p>
<p><strong>Shadow:</strong> misusing <code>soft delete</code> at rune 1640 in the naming lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>soft delete</code> when the prompt needs this obligation made explicit: <code>soft delete</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the soft delete obligation named before work proceeds.</li>
<li>Ask the assistant to state the <code>soft delete</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>soft delete</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
</section>
<section id="rune-1641" class="level3" data-number="114.2.59">
<h3 data-number="114.2.59" class="anchored" data-anchor-id="rune-1641"><span class="header-section-number">114.2.59</span> [1641] statefulset</h3>
<p><strong>Status:</strong> canonical</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> generated_draft</p>
<p><strong>Force:</strong> <code>statefulset</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the statefulset obligation named before work proceeds.</p>
<p><strong>Shadow:</strong> misusing <code>statefulset</code> at rune 1641 in the naming lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>statefulset</code> when the prompt needs this obligation made explicit: <code>statefulset</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the statefulset obligation named before work proceeds.</li>
<li>Ask the assistant to state the <code>statefulset</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>statefulset</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
</section>
<section id="rune-1642" class="level3" data-number="114.2.60">
<h3 data-number="114.2.60" class="anchored" data-anchor-id="rune-1642"><span class="header-section-number">114.2.60</span> [1642] write path</h3>
<p><strong>Status:</strong> canonical</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> generated_draft</p>
<p><strong>Force:</strong> <code>write path</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the write path obligation named before work proceeds.</p>
<p><strong>Shadow:</strong> misusing <code>write path</code> at rune 1642 in the naming lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>write path</code> when the prompt needs this obligation made explicit: <code>write path</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the write path obligation named before work proceeds.</li>
<li>Ask the assistant to state the <code>write path</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>write path</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
</section>
<section id="rune-1643" class="level3" data-number="114.2.61">
<h3 data-number="114.2.61" class="anchored" data-anchor-id="rune-1643"><span class="header-section-number">114.2.61</span> [1643] write-through cache</h3>
<p><strong>Status:</strong> canonical</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> generated_draft</p>
<p><strong>Force:</strong> <code>write-through cache</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the write-through cache obligation named before work proceeds.</p>
<p><strong>Shadow:</strong> misusing <code>write-through cache</code> at rune 1643 in the naming lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>write-through cache</code> when the prompt needs this obligation made explicit: <code>write-through cache</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the write-through cache obligation named before work proceeds.</li>
<li>Ask the assistant to state the <code>write-through cache</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>write-through cache</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
</section>
<section id="rune-1644" class="level3" data-number="114.2.62">
<h3 data-number="114.2.62" class="anchored" data-anchor-id="rune-1644"><span class="header-section-number">114.2.62</span> [1644] zero-downtime</h3>
<p><strong>Status:</strong> canonical (pocket canon)</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> reviewed</p>
<p><strong>Force:</strong> Change introduced without taking the service dark.</p>
<p><strong>Shadow:</strong> misusing <code>zero-downtime</code> at rune 1644 in the naming lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>zero-downtime</code> when the prompt needs this obligation made explicit: Change introduced without taking the service dark.</li>
<li>Ask the assistant to state the <code>zero-downtime</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>zero-downtime</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>
<p><strong>Pocket gloss:</strong> Change introduced without taking the service dark.</p>
</section>
<section id="rune-1645" class="level3" data-number="114.2.63">
<h3 data-number="114.2.63" class="anchored" data-anchor-id="rune-1645"><span class="header-section-number">114.2.63</span> [1645] zero-knowledge</h3>
<p><strong>Status:</strong> canonical</p>
<p><strong>Completion:</strong> authored</p>
<p><strong>Semantic status:</strong> generated_draft</p>
<p><strong>Force:</strong> <code>zero-knowledge</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the zero-knowledge obligation named before work proceeds.</p>
<p><strong>Shadow:</strong> misusing <code>zero-knowledge</code> at rune 1645 in the naming lane can let the modifier can imply a guarantee the base design has not earned; verify by requiring the caster to state the base term, modifier, and exact guarantee being added.</p>
<p><strong>Prompt uses:</strong></p>
<ul>
<li>Name <code>zero-knowledge</code> when the prompt needs this obligation made explicit: <code>zero-knowledge</code> is a compound naming and modifiers rune for make naming modifiers precise enough to carry engineering force; use it when the artifact needs the zero-knowledge obligation named before work proceeds.</li>
<li>Ask the assistant to state the <code>zero-knowledge</code> shadow before proposing changes.</li>
</ul>
<p><strong>Example clause:</strong></p>
<p>Before editing, state the <code>zero-knowledge</code> obligation, the evidence that satisfies it, and the failure mode if it is missing.</p>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/corbensorenson\.github\.io\/software-grimoire\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../reference/house-failure-words-pathologies-and-counter-spells.html" class="pagination-link" aria-label="Failure Words, Pathologies, and Counter-Spells">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">112</span>&nbsp; <span class="chapter-title">Failure Words, Pathologies, and Counter-Spells</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/corbensorenson/software-grimoire/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li><li><a href="https://github.com/corbensorenson/software-grimoire/blob/main/reference/house-compound-forms-prefixes-suffixes-and-naming-runes.qmd" class="toc-action"><i class="bi empty"></i>View source</a></li></ul></div></div></div></footer></body></html>